project:
  type: website

website:
  title: "MA Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

